"use strict";
exports.__esModule = true;
var Person_1 = require("./Person");
var Contact_1 = require("./Contact");
var persona = new Person_1.Person("Alvaro", "Montero", "Sanduval 35");
var persona2 = new Person_1.Person("Manuel", "Piris", "Tombola 33");
var persona3 = new Person_1.Person("Jorge", "HT", "Mordor 28");
var persona4 = new Person_1.Person("Ana", "Perez", "Alli a lo lejos");
console.log(persona);
console.log(persona2);
console.log(persona3);
console.log(persona4);
console.log(persona4.calcularIMC());
console.log(persona3.yearofBirth());
console.log(persona.printAll(persona));
persona2.printName();
console.log(persona3.getAdress());
persona3.setAdress("La calle del infierno");
console.log(persona3.getAdress());
var contacto = new Contact_1.Contacts();
contacto.contact.push(persona2);
contacto.printCalendar();
